import architecturalE from '../assets/Images/architectural engineering.jpg';
import chemicalE from '../assets/Images/chemical engineering.jpg';
import enviromantalE from '../assets/Images/enviromantal engineering.jpg';
import geotechnicalE from '../assets/Images/geotechnical engineering.jpg';
import computer_science from '../assets/Images/computer science.jpg';
import criminology from '../assets/Images/criminology.jpg';
import biology from '../assets/Images/biology.jpg';
import accounting from '../assets/Images/economics and accounting.jpg';
import capital_market from '../assets/Images/economics and capital market.jpeg';
import logistics from '../assets/Images/economics and logistics.jpeg';
import nursing from '../assets/Images/nursing.png';
import nutrition_science from '../assets/Images/nutrition science.jpg';
import psychology from '../assets/Images/psychology.jpg';
import public_health_care from '../assets/Images/public health care.png';
import sociology from '../assets/Images/sociology and anthropology.jpg';
import chemistry from '../assets/Images/chemistry.jpg';
const imagesGroup = [architecturalE,chemicalE,enviromantalE,geotechnicalE,computer_science,criminology,biology,accounting,capital_market,logistics,nursing,nutrition_science,psychology,public_health_care,sociology,chemistry];
export default imagesGroup;